kind: pipeline
type: docker
name: BowlIn


trigger:
  event:
    - push

steps:
  - name: code-analysis
    image: hub.codefirst.iut.uca.fr/thomas.bellembois/codefirst-dronesonarplugin-flutter 
    commands:
      - cd src/
# database container deployment
  - name: deploy-container-postgresql
    image: hub.codefirst.iut.uca.fr/thomas.bellembois/codefirst-dockerproxy-clientdrone:latest
    environment:
        IMAGENAME: postgres:latest
        CONTAINERNAME: postgresql
        COMMAND: create
        # OVERWRITE: false
        PRIVATE: true
        CODEFIRST_CLIENTDRONE_ENV_POSTGRES_ROOT_PASSWORD:
          from_secret: db_root_password
        CODEFIRST_CLIENTDRONE_ENV_POSTGRES_DB:
          from_secret: db_database
        CODEFIRST_CLIENTDRONE_ENV_POSTGRES_USER:
          from_secret: db_user
        CODEFIRST_CLIENTDRONE_ENV_POSTGRES_PASSWORD:
          from_secret: db_password
        ADMINS: emrekartal,louisonparant,davidd_almeida,lucasdelanier,arthurvalin
  - name: deploy-adminer
    image: hub.codefirst.iut.uca.fr/thomas.bellembois/codefirst-dockerproxy-clientdrone:latest
    environment:
      IMAGENAME: adminer
      CONTAINERNAME: adminer
      COMMAND: create
      OVERWRITE: true
      ADMINS: emrekartal,louisonparant,davidd_almeida,lucasdelanier,arthurvalin