kind: pipeline
type: docker
name: BowlIn


trigger:
  event:
    - push

steps:
# database container deployment
  - name: deploy-container-postgresql
    image: hub.codefirst.iut.uca.fr/thomas.bellembois/codefirst-dockerproxy-clientdrone:latest
    environment:
        IMAGENAME: postgres:latest
        CONTAINERNAME: postgresql
        COMMAND: create
        # OVERWRITE: false
        PRIVATE: true
        CODEFIRST_CLIENTDRONE_ENV_MARIADB_ROOT_PASSWORD:
          from_secret: db_root_password
        CODEFIRST_CLIENTDRONE_ENV_MARIADB_DATABASE:
          from_secret: db_database
        CODEFIRST_CLIENTDRONE_ENV_MARIADB_USER:
          from_secret: db_user
        CODEFIRST_CLIENTDRONE_ENV_MARIADB_PASSWORD:
          from_secret: db_password
  - name: deploy-adminer
    image: hub.codefirst.iut.uca.fr/thomas.bellembois/codefirst-dockerproxy-clientdrone:latest
    environment:
      IMAGENAME: adminer
      CONTAINERNAME: adminer
      COMMAND: create